apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: moraniacr01.azurecr.io/my-node-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
